module.exports = {
	flushQueue : require('./music.flushQueue.js'),
	getCurrentTrack : require('./music.getCurrentTrack.js'),
	getMuted : require('./music.getMuted.js'),
	getPlaying : require('./music.getPlaying.js'),
	getPlaylists : require('./music.getPlaylists.js'),
	getQueue : require('./music.getQueue.js'),
	getVolume : require('./music.getVolume.js'),
	next : require('./music.next.js'),
	pause : require('./music.pause.js'),
	play : require('./music.play.js'),
	playPlaylist : require('./music.playPlaylist.js'),
	previous : require('./music.previous.js'),
	setMuted : require('./music.setMuted.js'),
	setVolume : require('./music.setVolume.js'),
	stop : require('./music.stop.js'),
};